USE ROLE ACCOUNTADMIN;

GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE PURVIEW_SCAN_ROLE;
GRANT USAGE ON DATABASE RETAIL_DB TO ROLE PURVIEW_SCAN_ROLE;
GRANT USAGE ON SCHEMA RETAIL_DB.RAW TO ROLE PURVIEW_SCAN_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_DB.RAW TO ROLE PURVIEW_SCAN_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_DB.RAW TO ROLE PURVIEW_SCAN_ROLE;

GRANT ROLE PURVIEW_SCAN_ROLE TO USER rimsha;

ALTER USER rimsha SET DEFAULT_ROLE = PURVIEW_SCAN_ROLE;
ALTER USER rimsha SET DEFAULT_WAREHOUSE = DBT_WH;

SHOW GRANTS TO ROLE PURVIEW_SCAN_ROLE;
DESCRIBE USER rimsha;